name: Add issues and PRs to Sia project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Geçici adım
        run: echo 'Bu workflow şu an devre dışı, ileride düzenlenecek.'
    # uses: The-Bigfile/workflows/.github/workflows/project-add.yml@dev
    # secrets: inherit
    # Geçici olarak devre dışı bırakıldı, ileride tekrar düzenlenecek
